name: CakePHP_PHPUNIT

on: [push]

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: composer.jsonの構文確認
      run: composer validate

    - name: 依存関係のInstall
      run: composer install --prefer-dist --no-progress

    - name: PHPUNITテスト結果
      run: composer run-script test
